# Generated by Django 5.2.6 on 2025-10-16 10:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('group_type', models.CharField(choices=[('cell', 'Cellule de prière'), ('choir', 'Chorale'), ('youth', 'Jeunesse'), ('women', 'Femmes'), ('men', 'Hommes'), ('children', 'Enfants'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('meeting_day', models.CharField(blank=True, max_length=20, verbose_name='Jour de réunion')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='Heure de réunion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['group_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='ID Membre')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('marital_status', models.CharField(choices=[('single', 'Célibataire'), ('married', 'Conjoint(e)'), ('widowed', 'Veuf/Veuve'), ('divorced', 'Divorcé(e)')], max_length=20, verbose_name='État civil')),
                ('nationalite', models.CharField(blank=True, max_length=30, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('nombres_enfant', models.CharField(blank=True, max_length=5, null=True)),
                ('domaines', models.CharField(blank=True, choices=[('education', 'Éducation'), ('sante', 'Santé'), ('finance', 'Finance'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=50, null=True, verbose_name="Domaine d'activité")),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+227XXXXXXXX'. Jusqu'à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('membership_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'adhésion")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('visitor', 'Visiteur'), ('transferred', 'Transféré'), ('deceased', 'Décédé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='membres.family', verbose_name='Famille')),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='membres.group', verbose_name='Groupes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='membres.member', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='family',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_family', to='membres.member', verbose_name='Chef de famille'),
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du ministère')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_ministries', to='membres.member', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Ministère',
                'verbose_name_plural': 'Ministères',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='ministries',
            field=models.ManyToManyField(blank=True, related_name='members', to='membres.ministry', verbose_name='Ministères'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('event_type', models.CharField(choices=[('sunday_service', 'Culte dominical'), ('wednesday_service', 'Culte de mercredi'), ('prayer_meeting', 'Réunion de prière'), ('bible_study', 'Étude biblique'), ('special_event', 'Événement spécial'), ('other', 'Autre')], max_length=30, verbose_name="Type d'événement")),
                ('event_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'événement")),
                ('present', models.BooleanField(default=True, verbose_name='Présent')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='membres.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'member'],
                'unique_together': {('member', 'date', 'event_type')},
            },
        ),
    ]
