# Generated by Django 5.2.6 on 2025-10-16 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('category_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de transaction',
                'verbose_name_plural': 'Catégories de transactions',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('report_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel'), ('custom', 'Personnalisé')], max_length=20, verbose_name='Type de rapport')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des recettes')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des dépenses')),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde net')),
                ('report_data', models.JSONField(blank=True, default=dict, verbose_name='Données du rapport')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/financial/', verbose_name='Fichier PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='ID Transaction')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('transaction_type', models.CharField(choices=[('tithe', 'Dîme'), ('offering', 'Offrande'), ('donation', 'Don'), ('contribution', 'Cotisation'), ('special', 'Collecte spéciale'), ('expense', 'Dépense'), ('other', 'Autre')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement'), ('mobile', 'Mobile Money'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de reçu')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membres.family', verbose_name='Famille')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membres.group', verbose_name='Groupe')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membres.member', verbose_name='Membre')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transactioncategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du budget')),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel')], max_length=20, verbose_name='Période')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Mois')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('expected_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recettes prévues')),
                ('expected_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dépenses prévues')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-year', '-month'],
                'unique_together': {('period', 'year', 'month', 'quarter')},
            },
        ),
    ]
