# Generated by Django 5.2.6 on 2025-10-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_budget_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données du rapport'),
        ),
    ]
