# Generated by Django 5.2.6 on 2025-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_membre',
            field=models.BooleanField(default=True, verbose_name='Membre actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur principal'), ('secretary', 'Secrétaire'), ('treasurer', 'Trésorier'), ('leader', 'Responsable de groupe'), ('membre', 'Membre')], default='membre', max_length=20, verbose_name="Rôle de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
