# Generated by Django 5.2.6 on 2025-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_is_active_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Compte validé'),
        ),
    ]
